[tools]
node = "24"
"npm:@anthropic-ai/claude-code" = "latest"
"npm:@biomejs/biome" = "2.2.2"
"npm:pnpm" = "latest"
"npm:@sourcegraph/amp" = "latest"
python = "3.13"
ruby = "3.2.9"
rust = "latest"
uv = "latest"
bun = "1.2.23"
"npm:@openai/codex" = "latest"
"npm:eas-cli" = "latest"
usage = "latest"
java = "21"

[settings]
idiomatic_version_file_enable_tools = ["ruby", "python"]
