[tools]
node = "24"
"npm:@anthropic-ai/claude-code" = "latest"
"npm:@biomejs/biome" = "2.2.2"
"npm:pnpm" = "latest"
python = "3.13"
ruby = "3.2"
rust = "latest"
uv = "latest"

[settings]
idiomatic_version_file_enable_tools = ["ruby", "python"]
python.uv_venv_auto = true
